'use client';

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { RefreshCw, Send, X, Sparkles } from 'lucide-react';
import type { EmailItem } from '@/types';

interface DraftDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  item: EmailItem | null;
}

export function DraftDialog({ open, onOpenChange, item }: DraftDialogProps) {
  const [tone, setTone] = useState<'professional' | 'friendly' | 'brief'>('professional');
  const [draft, setDraft] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);

  const toneOptions = [
    { value: 'professional', label: 'Professional' },
    { value: 'friendly', label: 'Friendly' },
    { value: 'brief', label: 'Brief' },
  ] as const;

  const generateDraft = () => {
    setIsGenerating(true);
    // Simulate AI generation
    setTimeout(() => {
      const drafts = {
        professional: `Thank you for following up on the contract review. I understand the urgency with the client deadline today at 5pm.

I have reviewed the contract and everything looks good from my end. I am approving this for sign-off.

Please proceed with sending it to the client. Let me know if you need anything else.`,
        friendly: `Hey Sarah! Thanks for the heads up about the deadline.

I just took a look at the contract and it all checks out. You're good to go ahead and get that signed off!

Let me know if there's anything else I can help with. 😊`,
        brief: `Reviewed and approved. Please proceed with the sign-off.

Let me know if you need anything else.`,
      };
      setDraft(drafts[tone]);
      setIsGenerating(false);
      setIsGenerated(true);
    }, 1500);
  };

  const handleSend = () => {
    // Simulate sending
    alert('Email sent successfully! (Demo)');
    onOpenChange(false);
    setDraft('');
    setIsGenerated(false);
  };

  if (!item) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-amber-500" />
            Draft Reply
          </DialogTitle>
          <DialogDescription>
            Replying to: {item.subject}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Original email context */}
          <div className="bg-slate-50 rounded-lg p-3 text-sm">
            <p className="font-medium text-slate-700">From: {item.fromName}</p>
            <p className="text-slate-600 mt-1">&quot;{item.snippet}&quot;</p>
          </div>

          {/* Tone selector */}
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-slate-700">Tone:</span>
            {toneOptions.map((option) => (
              <Badge
                key={option.value}
                variant={tone === option.value ? 'default' : 'outline'}
                className="cursor-pointer"
                onClick={() => setTone(option.value)}
              >
                {option.label}
              </Badge>
            ))}
          </div>

          {/* Generate button */}
          {!isGenerated && (
            <Button 
              onClick={generateDraft} 
              disabled={isGenerating}
              className="w-full bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Generating with Bedrock...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Generate Draft with AI
                </>
              )}
            </Button>
          )}

          {/* Draft textarea */}
          {isGenerated && (
            <>
              <Textarea
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                placeholder="Your draft will appear here..."
                className="min-h-[200px]"
              />
              
              <div className="flex items-center gap-2 text-sm text-slate-500">
                <Sparkles className="h-4 w-4 text-amber-500" />
                Generated by Amazon Bedrock (Claude 3)
              </div>
            </>
          )}
        </div>

        <DialogFooter className="flex gap-2">
          {isGenerated && (
            <>
              <Button variant="outline" onClick={generateDraft}>
                <RefreshCw className="h-4 w-4 mr-2" />
                Regenerate
              </Button>
              <Button onClick={handleSend} className="bg-green-600 hover:bg-green-700">
                <Send className="h-4 w-4 mr-2" />
                Approve & Send
              </Button>
            </>
          )}
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            <X className="h-4 w-4 mr-2" />
            Cancel
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
